config/routes.rb
Rails.application.routes.draw do
  resources :categoria
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/categorium.rb
class Categorium < ApplicationRecord
		has_attached_file :imagen, styles: {large: "600x600>", medium: "300x300>", thumb: "100x100>"}, validate_media_type: false
  		validates_attachment_content_type :imagen, content_type: /\Aimage\/.*\z/

  		def imagen_url_medium
  			imagen.url(:medium)
  		end

  		def imagen_url_thumbnail
  			imagen.url(:thumb)
  		end
  		def imagen_url_large
  			imagen.url(:large)
  		end

end

app/models/usuario.rb
class Usuario < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categoria_controller.rb
class CategoriaController < ApplicationController
  before_action :set_categorium, only: [:show, :edit, :update, :destroy]

  # GET /categoria
  # GET /categoria.json
  def index
    @categoria = Categorium.all

    respond_to do |format|
      format.html
      format.json{render :json => @categoria.to_json(:only =>[:id,:nombre,:descripcion] ,:methods => [:imagen_url_thumbnail,:imagen_url_medium,:imagen_url_large])}
    end
  end

  # GET /categoria/1
  # GET /categoria/1.json
  def show
  end

  # GET /categoria/new
  def new
    @categorium = Categorium.new
  end

  # GET /categoria/1/edit
  def edit
  end

  # POST /categoria
  # POST /categoria.json
  def create
    @categorium = Categorium.new(categorium_params)

    respond_to do |format|
      if @categorium.save
        format.html { redirect_to @categorium, notice: 'Categorium was successfully created.' }
        format.json { render :show, status: :created, location: @categorium }
      else
        format.html { render :new }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categoria/1
  # PATCH/PUT /categoria/1.json
  def update
    respond_to do |format|
      if @categorium.update(categorium_params)
        format.html { redirect_to @categorium, notice: 'Categorium was successfully updated.' }
        format.json { render :show, status: :ok, location: @categorium }
      else
        format.html { render :edit }
        format.json { render json: @categorium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categoria/1
  # DELETE /categoria/1.json
  def destroy
    @categorium.destroy
    respond_to do |format|
      format.html { redirect_to categoria_url, notice: 'Categorium was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_categorium
      @categorium = Categorium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def categorium_params
      params.require(:categorium).permit(:nombre, :descripcion, :imagen)
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellidos, :correo, :password, :api_key, :fnacimiento, :sexo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/categoria/_form.html.erb
<%= form_with(model: categorium, local: true, html: { multipart: true })  do |form| %>
  <% if categorium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(categorium.errors.count, "error") %> prohibited this categorium from being saved:</h2>

      <ul>
      <% categorium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :categorium_nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_field :descripcion, id: :categorium_descripcion %>
  </div>
  <div class="field">
    <%= form.label :imagen %>
    <%= form.file_field :imagen, id: :categorium_image %>
  </div>
  
  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categoria/edit.html.erb
<h1>Editing Categorium</h1>

<%= render 'form', categorium: @categorium %>

<%= link_to 'Show', @categorium %> |
<%= link_to 'Back', categoria_path %>

app/views/categoria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categoria</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categoria.each do |categorium| %>
      <tr>
        <td><%= categorium.nombre %></td>
        <td><%= categorium.descripcion %></td>
        <td><%= link_to 'Show', categorium %></td>
        <td><%= link_to 'Edit', edit_categorium_path(categorium) %></td>
        <td><%= link_to 'Destroy', categorium, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Categorium', new_categorium_path %>

app/views/categoria/new.html.erb
<h1>New Categorium</h1>

<%= render 'form', categorium: @categorium %>

<%= link_to 'Back', categoria_path %>

app/views/categoria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @categorium.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @categorium.descripcion %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= image_tag @categorium.imagen.url(:thumb) %>
</p>

<p>
  <strong>Medium:</strong>
  <%= image_tag @categorium.imagen.url(:medium) %>
</p>

<p>
  <strong>Large:</strong>
  <%= image_tag @categorium.imagen.url(:large) %>
</p>

<%= link_to 'Edit', edit_categorium_path(@categorium) %> |
<%= link_to 'Back', categoria_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NearbyBackEnd</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :usuario_nombre %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos, id: :usuario_apellidos %>
  </div>

  <div class="field">
    <%= form.label :correo %>
    <%= form.text_field :correo, id: :usuario_correo %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password, id: :usuario_password %>
  </div>

  <div class="field">
    <%= form.label :api_key %>
    <%= form.text_field :api_key, id: :usuario_api_key %>
  </div>

  <div class="field">
    <%= form.label :fnacimiento %>
    <%= form.date_select :fnacimiento, id: :usuario_fnacimiento %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :usuario_sexo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Correo</th>
      <th>Password</th>
      <th>Api key</th>
      <th>Fnacimiento</th>
      <th>Sexo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellidos %></td>
        <td><%= usuario.correo %></td>
        <td><%= usuario.password %></td>
        <td><%= usuario.api_key %></td>
        <td><%= usuario.fnacimiento %></td>
        <td><%= usuario.sexo %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @usuario.apellidos %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @usuario.correo %>
</p>

<p>
  <strong>Password:</strong>
  <%= @usuario.password %>
</p>

<p>
  <strong>Api key:</strong>
  <%= @usuario.api_key %>
</p>

<p>
  <strong>Fnacimiento:</strong>
  <%= @usuario.fnacimiento %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @usuario.sexo %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>